### PR TITLE
Update code.py

### PR DESCRIPTION
**Pull request by donamath**
I have made some changes to your code. Please check them.

### CODE REVIEW

**Comment by donamath** [comment]
"Please enter initial number of contacts:"
What is the intended output of this query?

**Comment by Bhagya-Arbour** [comment]
for collecting the initial number of contacts the user wants to have in the contactbook

**Comment by donamath** [comment]
I think it's not needed. You can add contacts initially using the "Add contacts" option so that we can avoid ambiguity

**Comment by donamath** [comment]
If you are satisfied with my updations you can merge them or edit them.

**Pull request merged**
